### ISSUE TITLE
Is not a valid endorsement system chaincode

### ISSUE THREAD

**Issue by michielmulders** [hyperledger/caliper#149]
I'm getting the following error when running `node main.js -c config-fabric.json -n fabric.json` in `/benchmark/simple`. I want to test my Hyperledger chaincode, currently, I've not changed anything. I've run npm install and installed the required packages for Fabric: `npm install grpc@1.10.1 fabric-ca-client fabric-client`.

```
# create mychannel......
ok 1 created mychannel successfully
# Sleep 5s......
# Join channel......
# join mychannel
ok 2 Successfully joined mychannel
# install all chaincodes......
ok 3 Installed chaincode simple successfully in all peers
# Instantiate chaincode......
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
    at new createStatusError (/home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
    at new createStatusError (/home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
    at new createStatusError (/home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
    at new createStatusError (/home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/michiel/learning/hlf/caliper-benchmark/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
not ok 4 Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting... at Client.newDefaultKeyValueStore.then.then.then.then (/home/michiel/learning/hlf/caliper-benchmark/src/fabric/e2eUtils.js:372:19) at <anonymous> at Client.newDefaultKeyValueStore.then.then.then.then.then (/home/michiel/learning/hlf/caliper-benchmark/src/fabric/e2eUtils.js:385:15) at <anonymous>
  ---
    operator: fail
    at: chaincodes.reduce.then.catch (/home/michiel/learning/hlf/caliper-benchmark/src/fabric/instantiate-chaincode.js:60:19)
    stack: |-
      Error: Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
          at Client.newDefaultKeyValueStore.then.then.then.then (/home/michiel/learning/hlf/caliper-benchmark/src/fabric/e2eUtils.js:372:19)
          at <anonymous>
          at Client.newDefaultKeyValueStore.then.then.then.then.then (/home/michiel/learning/hlf/caliper-benchmark/src/fabric/e2eUtils.js:385:15)
          at <anonymous>
          at Test.assert [as _assert] (/home/michiel/learning/hlf/caliper-benchmark/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/michiel/learning/hlf/caliper-benchmark/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/michiel/learning/hlf/caliper-benchmark/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/michiel/learning/hlf/caliper-benchmark/node_modules/tape/lib/test.js:76:32)
          at chaincodes.reduce.then.catch (/home/michiel/learning/hlf/caliper-benchmark/src/fabric/instantiate-chaincode.js:60:19)
          at <anonymous>

```

**Comment by anfimovoleh** [comment]
Yes, have the same problem. Spend a lot of time, but not resolve this issue

**Comment by haojun** [comment]
It may be a sdk compatibility issue. Please install fabric sdk v1.1.0 and retry the test. For example, npm install grpc@1.10.1 fabric-ca-client@1.1.0 fabric-client@1.1.0

**Comment by michielmulders** [comment]
@haojun Yes that solves the issue, accurate answer!

**Comment by wompeter** [comment]
Another solution is to simply update the network to use containers matching the client/sdk version you are trying to test.

If you're running 1.2.0 for example, just go into `network/fabric/simplenetwork/docker-compose.yml`, and change all the image references from `hyperledger/fabric-peer:x86_64-1.1.0` to `hyperledger/fabric-peer:1.2.0`.

**Comment by lzh5261** [comment]
# create mychannel......
ok 1 created mychannel successfully
# Sleep 5s......
# Join channel......
# join mychannel
ok 2 Successfully joined mychannel
# install all chaincodes......
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/simple/go
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/simple/go
ok 3 Installed chaincode simple successfully in all peers
# Instantiate chaincode......
error: [Peer.js]: sendProposal - timed out after:120000
error: [Peer.js]: sendProposal - timed out after:120000
error: [Peer.js]: sendProposal - timed out after:120000
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/root/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/root/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/root/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
not ok 4 Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting... at Client.newDefaultKeyValueStore.then.then.then.then (/root/caliper/src/fabric/e2eUtils.js:372:19) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7) at Client.newDefaultKeyValueStore.then.then.then.then.then (/root/caliper/src/fabric/e2eUtils.js:385:15) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: chaincodes.reduce.then.catch (/root/caliper/src/fabric/instantiate-chaincode.js:60:19)
    stack: |-
      Error: Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
          at Client.newDefaultKeyValueStore.then.then.then.then (/root/caliper/src/fabric/e2eUtils.js:372:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Client.newDefaultKeyValueStore.then.then.then.then.then (/root/caliper/src/fabric/e2eUtils.js:385:15)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/root/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/root/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/root/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/root/caliper/node_modules/tape/lib/test.js:76:32)
          at chaincodes.reduce.then.catch (/root/caliper/src/fabric/instantiate-chaincode.js:60:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.installSmartContract() failed, Error: Fabric: instantiate chaincodes failed
    at chaincodes.reduce.then.catch (/root/caliper/src/fabric/instantiate-chaincode.js:61:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: instantiate chaincodes failed
    at chaincodes.reduce.then.catch (/root/caliper/src/fabric/instantiate-chaincode.js:61:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
Stopping peer1.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping peer1.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping orderer.example.com ... done
Stopping ca_peerOrg1 ... done
Stopping ca_peerOrg2 ... done
Stopping simplenetwork_ca_1 ... done
Removing peer1.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing peer1.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing simplenetwork_peer_1 ... done
Removing orderer.example.com ... done
Removing ca_peerOrg1 ... done
Removing ca_peerOrg2 ... done
Removing simplenetwork_ca_1 ... done
Removing network simplenetwork_default
daf7fbeb1870
a72b28b6aa82
89feb2493ff3
d7da8028f71c
b7982b562bc5
4d85531298cd
Untagged: dev-peer1.org1.example.com-simple-v0-2d56163f24dc127bcb48cf2dcdc1ac529d9164d868f9bbc2ce823e3a047dbc31:latest
Deleted: sha256:b77c47b1bdfbb8b19a315527fea24b02bd582e1e089e0280f874a3402fb1a6c2
Deleted: sha256:4abed7d2d900933b343859cbc3f41fb84857b3ecef5fd4aadef831b32d3caf7a
Deleted: sha256:b63255851f5b3687721c048c9f09feedcc8eef4a59170f8547b3842300afceb7
Deleted: sha256:e82bf183da6029666b5640329819e851a56270dbb3e021faa0d511a501832ae5
Untagged: dev-peer1.org2.example.com-simple-v0-7d068bf14ab99f7f01c1d580a3480868301e570c8b524a32918f99e2e241aa0a:latest
Deleted: sha256:65251cf8ff83b03094a66b8d8b85fb7aa72e076398f3cf58d9cf3c515849d6c7
Deleted: sha256:98663d2c17192cab196faa854d57111777247050d96a4f0e4084170cf7d4e6a8
Deleted: sha256:d2d17d15c46dde65f6f76b64cb75c4ba4de4762620c7277256e2d717b585a627
Deleted: sha256:3e5892ddce3d9b0fb519244e86aed61b34ec2dd51ececd40540d857a0d4f71dc
Untagged: dev-peer0.org2.example.com-simple-v0-7ebccf7a7fd05d8ac0a55ea61f1f0397ca89de629cef5f537c0950ecf302d423:latest
Deleted: sha256:0e3e42d273f1c55c6130f5c20d3fd2a78b68c39afa6ad5f4dd99f52c435a624a
Deleted: sha256:4afa17b1ace190886771fc30b3dec306eba251c812f9f9d96a5c1211da07c5e0
Deleted: sha256:b85a485702b6557cc8cbd2c7189f7bddb00d4448452f00a8d4f109b2c165d50d
Deleted: sha256:7405b6be5a383d766ab714dfc3d375fb822055c5bb88b40972bb81f5af52301f

1..4
# tests 4
# pass  3
# fail  1

Benchmark return code:  1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! caliper@0.1.0 e2e: `node ./scripts/test.js "simple" "./benchmark/simple/config.json" "./benchmark/simple/fabric.json"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the caliper@0.1.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-12T06_38_13_931Z-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by lzh5261** [comment]
i have installed golang,but still reported this mistake, which one step wrong ? please help solve i

**Comment by oralloj** [comment]
Is there any workaround for this issue when using IBM images instead of hyperledger's?
I need to use fabric sdk 1.2.x and it was working fine with hyperledger images, now I'm trying the same with IBM's and can't get past this error.

**Comment by nileshbhoskar** [comment]
I received same issue as below while starting server from Ubuntu local machine for every network,

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
Command failed

And if I create new network then it will work smoothly without any issue.

**Comment by PADMAARUN** [comment]
I received the following error while trying to run sample benchmark in hyperledger caliper

cse@system:~$ sudo npx caliper benchmark run --caliper-workspace ./ --caliper-benchconfig ~/caliper/packages/caliper-samples/benchmark/drm/config.yaml --caliper-networkconfig ~/caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
Benchmark for target Blockchain type fabric about to start
2019.11.29-16:28:51.888 info  [caliper] [caliper-flow] 	####### Caliper Test #######
2019.11.29-16:28:51.890 info  [caliper] [local-observer] 	Observer interval set to 1 seconds
2019.11.29-16:28:51.891 info  [caliper] [caliper-utils] 	Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yCreating orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org1.example.com ... done
Creating ca.org2.example.com ... 
Creating ca.org1.example.com ... 
Creating peer0.org2.example.com ... 
Creating peer0.org1.example.com ... 
2019.11.29-16:28:56.985 info  [caliper] [adapters/fabric] 	Fabric SDK version: 1.4.0; TLS: none
2019.11.29-16:28:57.353 info  [caliper] [adapters/fabric] 	Org1's registrar enrolled successfully
2019.11.29-16:28:57.514 info  [caliper] [adapters/fabric] 	Org2's registrar enrolled successfully
2019.11.29-16:28:57.541 info  [caliper] [adapters/fabric] 	Org1's admin's materials are successfully loaded
2019.11.29-16:28:57.545 info  [caliper] [adapters/fabric] 	Org2's admin's materials are successfully loaded
2019.11.29-16:28:57.550 info  [caliper] [adapters/fabric] 	client0.org1.example.com's materials are successfully loaded
2019.11.29-16:28:57.553 info  [caliper] [adapters/fabric] 	client0.org2.example.com's materials are successfully loaded
2019.11.29-16:28:57.554 info  [caliper] [adapters/fabric] 	Channel 'mychannel' definiton being retrieved from file
2019.11.29-16:28:57.587 info  [caliper] [adapters/fabric] 	Channel 'mychannel' successfully created
2019.11.29-16:28:57.587 info  [caliper] [adapters/fabric] 	Sleeping 5s...
2019.11.29-16:29:04.235 info  [caliper] [adapters/fabric] 	Org1's peers successfully joined mychannel: peer0.org1.example.com
2019.11.29-16:29:04.377 info  [caliper] [adapters/fabric] 	Org2's peers successfully joined mychannel: peer0.org2.example.com
2019.11.29-16:29:04.378 info  [caliper] [adapters/fabric] 	Sleeping 5s...
2019.11.29-16:29:09.382 info  [caliper] [adapters/fabric] 	Installing chaincodes for mychannel...
2019.11.29-16:29:09.429 info  [caliper] [adapters/fabric] 	marbles@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.29-16:29:09.441 info  [caliper] [adapters/fabric] 	marbles@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.29-16:29:09.454 info  [caliper] [adapters/fabric] 	drm@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.29-16:29:09.460 info  [caliper] [adapters/fabric] 	drm@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.29-16:29:09.475 info  [caliper] [adapters/fabric] 	simple@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.29-16:29:09.480 info  [caliper] [adapters/fabric] 	simple@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.29-16:29:09.493 info  [caliper] [adapters/fabric] 	smallbank@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.29-16:29:09.498 info  [caliper] [adapters/fabric] 	smallbank@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.29-16:29:09.498 info  [caliper] [adapters/fabric] 	Instantiating marbles@v0 in mychannel. This might take some time...
2019.11.29-16:29:10.463 info  [caliper] [adapters/fabric] 	Successfully instantiated marbles@v0 in mychannel
2019.11.29-16:29:10.466 info  [caliper] [adapters/fabric] 	Instantiating drm@v0 in mychannel. This might take some time...
2019.11.29-16:29:16.470 error [caliper] [caliper-flow] 	Error: Error: Invalid endorsement for drm@v0 in mychannel from peer0.org2.example.com: chaincode registration failed: container exited with 0
    at proposalResponses.forEach (/home/cse/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:1358:31)
    at Array.forEach (<anonymous>)
    at Fabric._instantiateChaincodes (/home/cse/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:1354:35)
    at <anonymous>
2019.11.29-16:29:17.473 info  [caliper] [local-observer] 	[undefined Round undefined Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
2019.11.29-16:29:17.474 info  [caliper] [caliper-utils] 	Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
Stopping peer0.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping ca.org1.example.com    ... done
Stopping orderer.example.com    ... done
Stopping ca.org2.example.com    ... done
Removing peer0.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing ca.org1.example.com    ... done
Removing orderer.example.com    ... done
Removing ca.org2.example.com    ... done
Removing network 2org1peergoleveldb_default
/bin/sh: 1: test: "4a8ff37c4fd1: unexpected operator
4a8ff37c4fd1
6aa8f6f7d17c
5d78f3f841f6
docker: "images" requires a maximum of 1 argument.
See 'docker images --help'.

Usage:	docker images [OPTIONS] [REPOSITORY[:TAG]]

List images
docker: "images" requires a maximum of 1 argument.
See 'docker images --help'.

Usage:	docker images [OPTIONS] [REPOSITORY[:TAG]]

List images
docker: "rmi" requires a minimum of 1 argument.
See 'docker rmi --help'.

Usage:	docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
Benchmark failure
Error: Benchmark failure
    at Function.handler (/home/cse/node_modules/@hyperledger/caliper-cli/lib/benchmark/lib/runBenchmark.js:70:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Command failed

**Comment by aklenik** [comment]
@PADMAARUN Check the peer logs to see why the chaincode registration has failed. Caliper (as a Fabric client) only receives a high-level error message
