### ISSUE TITLE
Configuring Fabric

### ISSUE THREAD

**Issue by jamievaravara** [hyperledger/caliper#154]
How can I edit the configuration of Fabric to generate various reports in Caliper?

What I want to change is the follwing:

1. Block size.
2. Block timeout.
3. The StateDB. 
4. Number of channels (I assume this requires me to add channel configs to the fabric config).
5. Endorsement policy. (N-OutOf, AND, OR) (also in fabric conf for each chaincode)?
6. Consensus protocol.
7. Data format stored in the StateDB.
8. Change the communication protocol between the docker containers, like change it from gossip to something else. (Data format used for communication between containers as well)

Also, can the StateDB be change to something else other than LevelDB and CouchDB?

Thank you very much.

**Comment by jamievaravara** [comment]
Block size and timeout can be changed through the channel config. How about the rest?

**Comment by jamievaravara** [comment]
Any help?

**Comment by aklenik** [comment]
@jamievaravara 4. and 5. can be configured from the Caliper side, as stated in the [related docs](https://hyperledger.github.io/caliper/docs/Fabric_Configuration.html). For the other points, refer to the Fabric project documentation and samples (or the Fabric SDK documentation for the endrosement policy).

Since these are questions rather than issues, I'm closing this thread. Feel free to ask further questions about the Caliper configurations in the [#caliper RocketChat channel](https://chat.hyperledger.org/channel/caliper), or through the mailing list: caliper@lists.hyperledger.org
