### ISSUE TITLE
How to benchmark a multi-hosts fabric network?

### ISSUE THREAD

**Issue by cao0507** [hyperledger/caliper#181]
In default, all the peers/orderer/CAs are run in the single host, but I want to spread these nodes to different hosts, so how to do that? Any advises would be appreciated !

**Comment by aklenik** [comment]
@cao0507 Using Caliper is completely independent of setting up the blockchain backend. The convenience `command.start` script simplifies setting up things in development time, but it is optional. 

You can connect to an already running remote Fabric network by setting the appropriate endpoints in the network config that is passed to Caliper.

An example network config can be found [here](https://github.com/hyperledger/caliper/blob/master/benchmark/simple/fabric-remote.json). Note the URLs of different nodes, they point to a remote location (DNS names can also be used).

Since this is an existing feature, I'm closing this issue.

**Comment by lakshaygaur** [comment]
@aklenik The fabric-remote.json file is not there anymore. Could you please share it again ?

**Comment by aklenik** [comment]
@lakshaygaur Yes, it's been removed, but you can take any file from the `network/fabric-v1.X/` directories. The only difference should be the url properties of the nodes. For example, a public IP and port instead of localhost.
