### ISSUE TITLE
test more client with caliper？

### ISSUE THREAD

**Issue by lybyyy** [hyperledger/caliper#267]
The simple only run 4 clients benchmark(i see client number 5 is defined in the file ./benchmark/simple/config.yaml, the document mentioned 1 is for sorting, and 4 is peer client, I modify the 5 to 9 to test 8 clients but it doesn't work...)
If I want to test 8 or even 32 clients, what should I do?

**Comment by houqinghui** [comment]
@lybyyy there are 5 clients in the default simple test ,  do you mean that you want to use more peers in the organitions?

**Comment by lybyyy** [comment]
@houqinghui
yes.
eg. Run 16 or more organizations and each organization has 2 or more peers.
what should i do? thank a lot.

**Comment by aklenik** [comment]
@lybyyy You should start by modifying one of the sample networks that Caliper provides. Including:
1. `configtx.yaml`
1. `crypto-config.yaml`
1. Regenerate the artifacts based on the above files
1. Add the new orgs and peers to the network configuration file that caliper uses.

Well, actually deploying the network is a little bit complicated, since you won't be able to run the network on a single machine (a looot of Docker container would be running). But if you already has that part, then you only need to modify the network config file that Caliper uses.

**Comment by wttat** [comment]
> @lybyyy You should start by modifying one of the sample networks that Caliper provides. Including:
> 
> 1. `configtx.yaml`
> 2. `crypto-config.yaml`
> 3. Regenerate the artifacts based on the above files
> 4. Add the new orgs and peers to the network configuration file that caliper uses.
> 
> Well, actually deploying the network is a little bit complicated, since you won't be able to run the network on a single machine (a looot of Docker container would be running). But if you already has that part, then you only need to modify the network config file that Caliper uses.

hello,I try to create a network that has 4org and 15peers in total , but when i tried to used the main.js to test my network it failed. I wonder it is because I used my fabric v1.3 folder clone from the fabric git to generate (make) the configtxgen and cryptogen bin fils and copy to caliper folder. Whats the correct step to 3.Regenerate the artifacts based on the above files?

I also tried not change the configtx.yaml and crypto-config.yaml ,only use the new configtxgen and cryptogen bin fils to regenerate the artifacts and it failed again.

here it looks like 

info: [create-channel.js]: Creating mychannel...
error: [Remote.js]: Error: Failed to connect before the deadline
error: [Orderer.js]: Orderer grpc://localhost:7050 has an error Error: Failed to connect before the deadline
error: [create-channel.js]: Failed to create channels: Error: Failed to connect before the deadline
    at checkState (/Users/wttat/caliper/caliper_orgin/node_modules/grpc/src/client.js:838:16)
error: [fabric.js]: Fabric initialization failed: Error: Failed to connect before the deadline
    at checkState (/Users/wttat/caliper/caliper_orgin/node_modules/grpc/src/client.js:838:16)
error: [bench-flow.js]: Error: Error: Failed to connect before the deadline
    at checkState (/Users/wttat/caliper/caliper_orgin/node_modules/grpc/src/client.js:838:16)
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0

**Comment by feihujiang** [comment]
This is an inactive issue for long time. So close it. @lybyyy If you still have the same problem, reopen it.
