### ISSUE TITLE
how to specify the endorser?

### ISSUE THREAD

**Issue by lenoAlex** [hyperledger/caliper#292]
for example, using 2org2peer of network, how to specify one peer in each org to endorse a transaction?
In another word, there are four peers, but only need two peers to process endorsement. Could it be configurable on caliper?

**Comment by houqinghui** [comment]
@lenoAlex  The endorsement-policy defines the endorsement policy for all the chaincodes. Currently, only one policy can be defined and the policy is applied to all chaincodes. You can refer to https://hyperledger.github.io/caliper/docs/Fabric_Configuration.html and https://hyperledger-fabric.readthedocs.io/en/release-1.3/endorsement-policies.html

**Comment by feihujiang** [comment]
As the fabric documentation says "if no single peer is preferable based on the criteria, the fabric client SDK will randomly select from the peers that best meet the criteria", so Caliper now uses random peers ( one peer per organization ) as endorsers as default. Here is [the related fabric documentation's link](https://hyperledger-fabric.readthedocs.io/en/release-1.4/discovery-overview.html#how-service-discovery-works-in-fabric).

**Comment by lenoAlex** [comment]
@houqinghui @feihujiang if caliper can use peer which is specified by users and configurable to endorse, that could be better, i think.

**Comment by feihujiang** [comment]
@lenoAlex In Caliper latest version, target peers are chosen using `peers[clientIdx % peers.length]` which would cycle the client connections through the available peers . #255

**Comment by lenoAlex** [comment]
@feihujiang as far as I known, caliper uses interface "sendTransactionProposal(request, timeout)" of SDK to send  request of endorsement. And the arg, "targets" , of the struct , "ChaincodeInvokeRequest",  specifies a peer to endorse.

**Comment by aklenik** [comment]
@lenoAlex The `fabric` adapter in Caliper uses an automatic client process-based load balancing between the possible peers of an organization. You have the following options:

1. If you don't want a peer to endorse transactions, just leave it out of the configuration file. Con: it definitely won't endorse, since Caliper can't "see" it.
1. If you add a peer to the configuration, it will be part of the automatic load balancing between peers. Con: you can affect the targets.
1. Check out the new `fabric-ccp` adapter #296 that allows the user callback to specify the target endorsers explicitly on a per-transactions basis. If not specified, then a (configurable) client- or transaction-based load balancing is used.

**Comment by lenoAlex** [comment]
@aklenik ， I got it, thank you.
