### ISSUE TITLE
[consult]endorsement-policy "member" and "admin"

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#309]
## Context
When I lookup some configuration in official website of Caliper and some other engineers' blog, I found that for endorsement-policy, there is some minor difference.
Could you tell me what is the difference of the following two configuration:
![ff84622a399703697bfce1f50a07a4c](https://user-images.githubusercontent.com/12689769/52844306-40b7d180-313f-11e9-8704-608dc427a069.png)
And
![0dba0ef9d6eac55712cfc5e73672a30](https://user-images.githubusercontent.com/12689769/52844315-49100c80-313f-11e9-97e5-3b3d4b4a1838.png)

Thanks.

**Comment by aklenik** [comment]
@CoreyLin Technically, nothing. The `identities` property lists some identities of different MSPs in an array, so it's easier to reference them (with a 0-based index) in the `policy` section.

The actual policy expression (that needs to be satisfied by the collected endorsement signatures) are the same in both cases. And I don't just mean they're the same character-by-character, but the indices also reference the same identities (Org1MSP.member and Org2MSP.member).

NB: you see the first example on may sites because it shows the possibility of defining admin signature requirements. I think it was me who removed the admin role from the Caliper-provided example configurations because it wasn't referenced.

**Comment by CoreyLin** [comment]
@aklenik Thanks very much. One furthur question: you mentioned that "I think it was me who removed the admin role from the Caliper-provided example configurations because it wasn't referenced". Does this mean that admin role is actually no use here, right?

**Comment by aklenik** [comment]
@CoreyLin None of the example chaincodes requires it. It all depends on the certs and keys of the peers that sign the endorsements. You need to use the roles of those certs (SomeMSP.member includes the peer role I think, but I need to look into this).

**Comment by CoreyLin** [comment]
@aklenik Got it. Thanks very much.
