### ISSUE TITLE
The actual Send Rate is not equal to the configured fixed-rate

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#319]
## Context
The context and env is totally same as #314
The configured send rate of "query" label is 5:
![9ba139efd9cf21563aa2aef396b91f1](https://user-images.githubusercontent.com/12689769/52895794-2f7fcb00-31fa-11e9-857e-2bff7c9d472f.png)
But in the test log, the send rate is about 7.5:
![b6585afd16337d78a761fdf8f9878c8](https://user-images.githubusercontent.com/12689769/52895814-71a90c80-31fa-11e9-8741-f864999eecd8.png)
![7c848f9482409eafceb86817c174454](https://user-images.githubusercontent.com/12689769/52895816-75d52a00-31fa-11e9-9bc9-541c8f008366.png)
Could you please check it? Thanks. :blush:

**Comment by aklenik** [comment]
The send rate is divided among the clients (5 clients by default). Together with the timing calculations, this can cause some deviation from the specified send rate. Usually this is a relatively small deviation (2,5 TPS), but since the send rate is 5 TPS, you notice this difference. Can you confirm, that a relatively high deviation is observable with higher send rates?

**Comment by CoreyLin** [comment]
@aklenik Thanks for your explanation. Actually for higher send rates, I didn't discovered a large deviation, and the deviation remians within 0.6 tps in my env. So I think 2.5 TPS can be accepted, after all, I only configure 5 TPS(very small).

**Comment by csd3458** [comment]
After setting the fixed rate to 100TPS the send rate is 81.4
Whats the problem?
Thanks in advance
