### ISSUE TITLE
specifying multiple endorsers from a same org in caliper?

### ISSUE THREAD

**Issue by paramesh** [hyperledger/caliper#322]
## Context
Incase of network having 1Org and 2peer per Org. Is it possible to specify that every transaction should be endorsed by all the four peers? (all the peers in all the orgs?)

We tried the following configuration but it does not seem to work.
"endorsement-policy": {
      "identities": [
        {
          "role": {
            "name": "member",
            "mspId": "Org1MSP"
          }
        },
        {
          "role": {
            "name": "member",
            "mspId": "Org1MSP"
          }
        }
      ],
      "policy": {"2-of":[{"signed-by" : 0}, { "signed-by" : 1}]}

**Comment by paramesh** [comment]
Incase of network having 2Org and 2peer per Org. Is it possible to specify that every transaction should be endorsed by all the four peers? (all the peers in all the orgs?)

**Comment by houqinghui** [comment]
@paramesh  I cannot get your point. do you mean that you havar 2 Orgs and 2 peers per Org and how do you write the endorsement-policy when you want every transcations to be endorsed by all the four peers?

**Comment by paramesh** [comment]
@houqinghui yes you are right.

**Comment by houqinghui** [comment]
@paramesh You can refer to the [endorsement policy ](https://hyperledger-fabric.readthedocs.io/en/latest/endorsement-policies.html)of the fabric documentation.

**Comment by aklenik** [comment]
@paramesh The peers are "just" resources contributed by organizations. The consensus happens between organizations and not peers. The number of peers is a perfomance scaling parameter, the policies are defined on the organization level (otherwise you'd need to modify a chaincode's endorsement policy every time you add a new peer to the network).

That being said, nothing prevents you from sending the transaction proposal to multiple peers from the same orgs, but only one of the returned endorsements are needed for the endorsement policy, so it's kind of a waste of resources in a normal scenario.

From a technical point of view: Caliper sends a proposal to only one peer per org (based on the above reasoning). The new Fabric adapter (PR #296) allows you to specify any target if you want to execute a transaction on every peer (but it won't affect the validation of the endorsement policy).

**Comment by paramesh** [comment]
Thanks @houqinghui @aklenik
