### ISSUE TITLE
The success of channel creation should be verified.

### ISSUE THREAD

**Issue by clumsky** [hyperledger/caliper#326]
In caliper/src/adapters/fabric/create-channel.js. line120:
const result = await client.createChannel(request);

## Context

The Hyperledger Fabric SDK for Node.js  API  introduces class Client createChannel(request)
Returns:
Promise for a result object with status on the acceptance of the create request by the orderer. Note that this is not the confirmation of successful creation of the channel. The client application must poll the orderer to discover whether the channel has been created completely or not.

## Expected Behavior

After client create channel, verifying whether the channel has been created completely. 

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by aklenik** [comment]
@clumsky As far as I know, Fabric doesn't provide an API for querying the channels for privacy reasons. The only query you can make is asking a peer what channels it has joined. So joining a channel is the only viable way to check whether a channel is successfully created or not.

From a technical point of view (I'm not entirely confident in these details, but [this page](https://hyperledger-fabric.readthedocs.io/en/latest/network/network.html) describes a similar story): creating a channel with/through the orderer is kind of a lightweight operation (a new topic in Kafka, a config block and similar housekeepings). The heavier part is when a peer joins a channel and instantiates the related artifacts locally. So since channels are just logical concepts, joining is where the critical stuff happens.

Is this reasoning acceptable?

**Comment by clumsky** [comment]
@aklenik  what is the meanig of "The client application must poll the orderer to discover whether the channel has been created completely or not."? when we can poll the orderer to verify channel has been created?

**Comment by aklenik** [comment]
@clumsky I've also been wondering about that, but couldn't find any SDK-provided API for this polling. Only the mentioned query about which channels a peer has joined.

Maybe you could ask around some Fabric SDK-specific RocketChat channel or mailing list and update your findings here for future reference.
