### ISSUE TITLE
When fabric network is created, caliper don't need to execute command. 

### ISSUE THREAD

**Issue by clumsky** [hyperledger/caliper#329]
## Context

For example,user use caliper to run benchmark/simple.
node main.js -n ../../network/fabric-v1.1/2org1peergoleveldb/fabric-go.json 
test run success.
But when use has own fabric network, user don't need to create default fabric network. Now the solution is user modify fabric-go.json to remove caliper.command.start and caliper.command.end.
## Expected Behavior

User  use node main.js -argv  -n ../../network/fabric-v1.1/2org1peergoleveldb/fabric-go.json  to start testing. The argv can control whether creating the default fabric network. 
## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by aklenik** [comment]
@clumsky The start and end commands can contain arbitrary scripts, not just network starting/cleaning ones. But I agree with your point, that during development, it would be convenient to optionally skip the start and/or end scripts.

I'll write a separate issue about this soon, and you can edit your PR accordingly (because there is a nicer way for this setting :) )
