### ISSUE TITLE
Support detailed latency information

### ISSUE THREAD

**Issue by narsimplyme** [hyperledger/caliper#407]
## Context

Currently, the default Caliper benchmarks shows result like "Max latency", "Min Latency", and "Avg Latency". But I wish I could get more data from the transaction step-by-step. 
For example; HLF(https://hyperledger-fabric.readthedocs.io/en/latest/txflow.html) has Peers & Orderers that are involved in the transaction flow.
It'll be great if we can get the latency from each step, so we could get a real insight of the blockchain and see what is creating a bottleneck or where we're needing a improvement

I've seen fabric-test/PTE but never was able to run a actual bench.
this was what I was expecting as a benchmarking tool, but too bad I couldn't run it.
(https://github.com/hyperledger/fabric-test/tree/master/tools/PTE)

## Expected Behavior

Network Latency : Max/Min/Avg
Peer Latency : Max/Min/Avg
Orderer Latency : Max/Min/Avg
E2E Latency : Max/Min/Avg

## Actual Behavior

Only the E2E results?
## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Your Environment

* Version used: HLF 1.4 with kafka/zookeeper based 3 Orderer
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): CentOS 7
* Link to your project:

**Comment by aklenik** [comment]
@narsimplyme Both Fabric adapters collect detailed timing data about the transaction life-cycle. See the Fabric-CCP adapter docs: https://hyperledger.github.io/caliper/docs/Fabric_Ccp_Configuration.html#transaction-data-gathered-by-the-adapter

I think this set of data contains every information that is observable by a client (Caliper in this case). But it can't separate the ordering and validation time since there is no event notification for when an orderer broadcasts a block. You need your own toolset to get these timings: log mining, inspect network traffic, or whatever you can think of. I'd also be interested if you find a way for this :)
