### ISSUE TITLE
Benchmark flow needs to be split

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#422]
The benchmark flow needs to be refined in order to enable conditional execution of flow elements, which are controlled by the config file.

It should be possible to conditionally perform all benchmark flow stages, most notably the:
- init
- installSmartContract

My recommendation would be to conditionally execute the above based on config parameters within the main run section of the caliper flow.

This would enable a user to easily run a benchmark on a network that has been initialised and had a smart contract installed

**Comment by aklenik** [comment]
@nklincoln I've worked on the runtime config parts, I'll also add this decision points with the new config mechanism. 

Question/suggestion:
Do we need to separate the two steps? Can't we just say that an adapter provides an `init` step? The sawtooth adapter doesn't do anything for the `installSmartContract`. So an adapter should encapsulate what it means by init. So the Fabric adapter could allow skipping channel creations as well as chaincode deployment (the CCP adapter checks the latter automatically).

**Comment by nklincoln** [comment]
Having a single `init` could make things a little more concise, especially if the `installSmartContract` method is redundant in some cases

**Comment by aklenik** [comment]
@nklincoln yes, I've looked at this function. But it only tells what channels that peer has joined. Even if I query this for every peer, it's not a guarantee that the channel doesn't exist. Unless I get back that a peer is part of that channel (and this last part could be added to the adapter for convenience)

But I don't know of a correct way to check whether a channel exists or not, since it is supposed to be a sensitive information.

**Comment by nklincoln** [comment]
this is now duplicated by #535
