### ISSUE TITLE
configtx.yaml of Fabric1.4 cannot pass the formatting check

### ISSUE THREAD

**Issue by CaiusBallad** [hyperledger/caliper#477]
## Context

I found caliper/packages/caliper-samples/network/fabric-v1.4/config/configtx.yaml  cannot pass the **formatting check.**
And I am confused that why all the AnchorPeers of  three Org(1,2,3) are the same Port 
## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Your Environment

* Version used: latest version
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by aklenik** [comment]
@CaiusBallad 
1. What do you mean by formatting checks? Some editor complains because the YAML anchors are referenced before they're actually declared. Just move the profiles section to the end to get rid of these "errors".
1. Because each anchor peer uses the same port on the Docker container/network level. The confusion probably comes from the fact, that Caliper connects to them on different ports. That's because Caliper is not inside the Docker network, so it uses different ports on the Docker boundary that are mapped to the same port numbers of _different_ containers. So the ports are just one part of the node endpoints.

**Comment by 54ZBD** [comment]
Have you succeed at Installing Caliper 1.4 ？

**Comment by 54ZBD** [comment]
@Have you succeed at Installing Caliper 1.4 ？

**Comment by CaiusBallad** [comment]
yes------------------ 原始邮件 ------------------
发件人: "54ZBD"<notifications@github.com>
发送时间: 2019年7月8日(星期一) 上午10:35
收件人: "hyperledger/caliper"<caliper@noreply.github.com>;
抄送: "Long"<longjieiyi@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [hyperledger/caliper] configtx.yaml of Fabric1.4 cannot pass theformatting check (#477)



@have you succeed at Installing Caliper 1.4 ？
 
&mdash;

**Comment by 54ZBD** [comment]
i have trouble when installing Cli 1.4, could you give some help ?Any help would be greatly appreciated! my qq number is 1213737146. thx

**Comment by aklenik** [comment]
@CaiusBallad I'm closing this thread (since actual bugs were not reported), feel free to continue the discussion on Rocket chat or the mailing list
