### ISSUE TITLE
composer.installSmartContract() failed

### ISSUE THREAD

**Issue by AUQIB92** [hyperledger/caliper#494]
Starting business network basic-sample-network. This involves building chaincode containers and may take several minutes to complete... composer.installSmartContract() failed,  Error: Error trying to start business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN npm ERR! errno EAI_AGAIN

**Comment by aklenik** [comment]
@AUQIB92 Which benchmark did you run? What are your environment specs? `EAI_AGAIN` indicates a temporary failure in name resolution when installing a package. And since this occurred when building a docker container, I guess it is a backend error during chaincode deployment. Check the peer logs for anything specific and the packages you use in your BNA transaction logic file.
