### ISSUE TITLE
Incorrect CPU percent statistics for local docker container

### ISSUE THREAD

**Issue by vita-dounai** [hyperledger/caliper#504]
## Context

I set up a 4 blockchain nodes benchmark in which all nodes running in local docker containers. Although my machine has only 8 cores, the CPU percent statistics return by Caliper shows that the CPU usage percentage of each container had been beyond 1500%, it's not reasonable.

## Expected Behavior

The CPU usage percentage of each node container should not exceed 800% with a 8 cores CPU.

## Actual Behavior

![image](https://user-images.githubusercontent.com/44284897/61099183-0ce59b80-a494-11e9-967b-0444ee04bb5f.png)

## Possible Fix

The way to calculate CPU usage for local docker container should be same as remote docker container.

## Steps to Reproduce

1. Install Caliper and Caliper CLI
2. Run a benchmark
3. View performance statistics result

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Context

This problem make that Caliper can't afford accurate  CPU usage statistics for me. When I try to copy code for calculating CPU usage from the code block for remote docker container, the problem is solved.

## Your Environment

* Caliper version: v0.1.0
* NodeJS version: v8.16.0, Docker version: v18.09.7
* Operating System and version: Ubuntu Server 18.04 LTS
* Link to your project: https://github.com/vita-dounai/caliper/tree/fisco-bcos

**Comment by aklenik** [comment]
Yes, you're absolutely right. There's an ongoing debate about the scope of Caliper. Specifically, whether it should collect such data at all. There're many industrial-grade tools available for resource monitoring, with a seamless integration pipeline between different tools (from metric collection to visualization). 

So in the long term, it's possible that resource monitoring will be removed from Caliper, and it will only collect the client-side transaction metrics, as defined by the PSWG whitepaper. We'll see. We certainly don't want to reinvent the wheel (nor we have the resources for it). 

However, in the meantime, we'd really appreciate if you'd open a PR with the fix since it looks like you got it working :)

**Comment by aklenik** [comment]
Resolved by #508
