### ISSUE TITLE
Error while performing "install" step: Error: Could not install marbles@v0 on some peers of mychannel

### ISSUE THREAD

**Issue by HelmiTrabelsi** [hyperledger/caliper#810]
## Context

I cloned the last version of caliper-benshmarks folder and tried to run a benshmark on Fabric2.0 after bounding to SDK version 1.4.5 but get an error when instaling marbles chaincode

## Actual Behavior

error [caliper] [adapters/fabric] 	Could not install marbles@v0 on some peers of mychannel:
	- Install proposal error for marbles@v0 on peer0.org1.example.com: could not build chaincode: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "/chaincode/input/src/fabric/samples/marbles/go/marbles.go:110:2: cannot find package "github.com/github.com/hyperledger/fabric-chaincode-go/shim" in any of:
	/usr/local/go/src/github.com/github.com/hyperledger/fabric-chaincode-go/shim (from $GOROOT)
	/chaincode/input/src/github.com/github.com/hyperledger/fabric-chaincode-go/shim (from $GOPATH)
	/go/src/github.com/github.com/hyperledger/fabric-chaincode-go/shim
/chaincode/input/src/fabric/samples/marbles/go/marbles.go:111:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
	/go/src/github.com/hyperledger/fabric/protos/peer

## Your Environment

* caliper: v0.3.0
* Fabric: v2.0
* Operating System: Ubuntu

**Comment by aklenik** [comment]
@HelmiTrabelsi Channel and chaincode management for Fabric v2 are not supported by Caliper (because they're not supported by the Fabric SDK). Plus if I recall correctly, the shim modules are no longer vendored automatically by Fabric, so you must vendor them yourself. 
So you must perform every network initialization outside of Caliper (using the Fabric `peer` binary), then run a test-only benchmark with Caliper. For the Fabric initialization details, refer to the Fabric docs, or a Fabric-related forum.

**Comment by harisjavaid85** [comment]
@aklenik I encountered the same issue. My setup involves Caliper v0.3.2 with Fabric SDK 1.4.5 binding, while my SUT (the peers) runs Fabric v2.1.0 without V2_0 capabilities (did not set the capabilities flag V2_0 in configtx.yaml file). My understanding from the documentation is that Fabric SDK 1.4.x is compatible with Fabric SUT 2.1.x, so Caliper should have been able to create channel and install the chaincode. However, channel creation is fine but the installation of chaincode fails with the above error.

If Fabric SDK 1.4.5 bound in Caliper is using old style chaincode install/instantiation, then why does it fail with Fabric SUT 2.1.0? Can you explain further, thanks!

**Comment by harisjavaid85** [comment]
I figured out the issue with my setup. I had tagged the docker image `hyperledger/fabric-ccenv:1.4.5` as latest so that the peer could use 1.4.5 version when building the chaincode. It turns out that this behaviour has changed (I got a hint from [this post](https://stackoverflow.com/questions/63773688/cannot-install-chaincode-using-hurley-hyperledger-fabric)). The solution is to set the env variable `CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.5` when bringing up the peer. After that, Caliper was able to both install and instantiate the chaincode and the benchmark test was successful.

**Comment by gompopcorn** [comment]
I also have done the same trick(Change the tag of the image to latest), and had problem. I think my problem will be solved by your solution. But I can't find where to set CORE_CHAINCODE_BUILDER env variable.
Thank in advance for your help

**Comment by Alireza-HN** [comment]
I also have done the same trick(Change the tag of the image to latest), and had problem. I think my problem will be solved by your solution. But I can't find where to set CORE_CHAINCODE_BUILDER env variable.
Thank in advance for your help

**Comment by harisjavaid85** [comment]
You can set this env variable in the docker-compose file inside the environment section of the peer docker.
