### ISSUE TITLE
Different throughput results according to the number of worker processes

### ISSUE THREAD

**Issue by KimYongTTT** [hyperledger/caliper#851]
Different throughput results according to the number of worker processes

## Context

[Performance test for HLF v2.1.0 with caliper-v0.3.1 , simple chaincode]
Doing test in distributed environment, with remote worker processes for generating workloads.
While testing, I found bottleneck with caliper to generate 40,000 > sendRate in query phase.
To solve that problem I increased the number of total worker processes from (6nodes, 96processes) to (6nodes, 144processes)
It solved generating more than 40,000 sendRate but i found that chaincode invoke(simple/open) phase's throughput decreased while doing same round with same benchmark config file.

## Expected Behavior

Since a worker process is for generating input workloads, Hyperledger Fabric 's throughput with same rate option should not change due to the number of worker processes.

## Actual Behavior

Using same environment, just changed benchmark config file's worker number from 96 to 144.
You can see that overall throughput decreased and the maximum throughput decreased from 4200 to 4000
<<<<< Reports with 96 workers >>>>>>

![image](https://user-images.githubusercontent.com/39793010/83600757-3dea2580-a5aa-11ea-895d-3f5f6063d652.png)

<<<<< Reports with 144 workers >>>>>>

![image](https://user-images.githubusercontent.com/39793010/83600906-95889100-a5aa-11ea-8a5e-caf49fc150a9.png)

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Your Environment

* Version used:  caliper v0.3.1
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by nklincoln** [comment]
Hi @KimYongTTT ,
Thanks for the above information, can you provide information on the rate control configuration that you were using to achieve the above? It would help us if we knew what the benchmark round  driving rate was in both instances

**Comment by KimYongTTT** [comment]
Hi @nklincoln , Thanks for your reply 👍 
I'm doing benchmark test with fixed-rate options during 10 rounds.
Increasing tps from 3800~4700 (100 tps interval)
Only difference was the number of workers (96 or 144).
Below is the part of my config file. 


--------------------------------- Benchmark config------------------------------------

test:
  name: simple ( HLF v2.1.0 (SDK v2.1.0) Level DB )
  description: This is a benchmark to test the raft ordering service
    performance with simple account opening & querying transactions
  workers:
    number: 96

  rounds:
  - label: void
    txDuration: 20
    rateControl:
      type: zero-rate
      opts:
    arguments:
      money: 10000
    callback: /hyperledger/perftest-v2.x/workload-modules/simple/open.js

  - label: open1
    txDuration: 20
    rateControl:
      type: fixed-rate
      opts:
        tps: 3800
    arguments:
      money: 10000
    callback: /hyperledger/perftest-v2.x/workload-modules/simple/open.js

  - label: open2
    txDuration: 20
    rateControl:
      type: fixed-rate
      opts:
        tps: 3900
    arguments:
      money: 10000
    callback: /hyperledger/perftest-v2.x/workload-modules/simple/open.js

  - label: open3
    txDuration: 20
    rateControl:
      type: fixed-rate
      opts:
        tps: 4000
    arguments:
      money: 10000
    callback: /hyperledger/perftest-v2.x/workload-modules/simple/open.js

  - label: open4
    txDuration: 20
    rateControl:
      type: fixed-rate
      opts:
        tps: 4100
    arguments:
      money: 10000
    callback: /hyperledger/perftest-v2.x/workload-modules/simple/open.js

**Comment by aklenik** [comment]
@KimYongTTT The statement that "the number of workers shouldn't make a difference as long as the sending rate is the same" is not true. A worker process will create a connection profile for every identity in the config. While the actual connections are lazy-loaded in the profiles, you still use at least one identity per worker. 

So the active connections maintained towards Fabric are increased (both the client connections and the subscriptions for the eventing service). Maybe this causes the observed drop in throughput. So the question is the Fabric throughput sensitivity to the number of actively maintained connections.

**Comment by KimYongTTT** [comment]
Hi @aklenik thanks for the information :)
So to conclude your opinion, above result is not caliper's problem but it possibly was derived from a difference in the number of client's connections between the HLF network.
Then how about giving users a guide or explanation about this for their fair performance test?
Or if you have any insights about doing a fair benchmark test with increased/decreased worker process' number, please let me know.

**Comment by aklenik** [comment]
@KimYongTTT Well, fair benchmarking is a complicated topic. If you take a look at some standard benchmark specifications (like TPC-C), they almost always contain a workload specification, not just the application/server-side description.

The number of emulated clients (sometimes called as remote terminals) is usually proportional to the scale of the benchmark (whatever that means, e.g., SUT node number, database size, etc.). Since maintaining client connections has some overhead, it can be an important part of the benchmark.

So far I haven't seen a detailed study on the performance overhead of client connections in Fabric, so that's why such a guide is missing. Moreover, strictly speaking, Caliper is not about providing performance tuning guides to DLTs, it's just a tool you can use to benchmark DLTs and write said guidelines based on the results (and on probably more detailed profiling).

Back to the Fabric adapter. There will be at least one connection for the used identity per worker, assuming that the v2 gateway approach still uses lazy-loading of connections (maybe @nklincoln can shed some light on this). Plus you have the event service connections, which can be adjusted on a channel basis:
https://github.com/hyperledger/caliper/blob/d0507aa64e9df33c3be6d9bc5c001800712c6dbd/packages/caliper-tests-integration/fabric_tests/phase4/networkconfig.yaml#L53-L57
The event service subscriptions are done in the `getContext` function of the Fabric adapters, so you can look there for the specifics. 

You are right that these should be configurable to the last connection, but we are not there yet. So feel free to experiment with the connection management, and let us know if you found a way to improve it. 

(I'm closing this "issue", but feel free to continue the discussion in this thread.)
