### ISSUE TITLE
configValidator needs to support changes to the connection profile undocumented specification

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#989]
With the advent of the new fabric adapter configuration the need to validate the network config based on a version of the ccp will be removed, however for now because the fabric network configuration file has to be a superset of the connection profile, the fabric config validator needs to be changed to validate to the newly undocumented standard that has recently occurred, in order to not make it harder to create a network_config from a ccp.
`tlsCACerts/pem` property now can be either a string or an array of strings and in the latest version of test-network it would appear that it's been decided that the CA definition should use the array format and all the others should use string form which has an impact on the 0.4 tutorial.

Options:
- Update tutorial
- Update validator, and fabric-network class

**Comment by huytran1ibm** [comment]
Also for fabric v2 and using the phase2 test sample network.yaml, I am getting a validation error

`Error [ValidationError]: child "version" fails because ["version" must be one of [1.0]]. child "clients" fails because ["clients" is required]. child "channels" fails because ["channels" must be an object]. child "organizations" fails because ["organizations" must be an object]. child "orderers" fails because ["orderers" is required]. child "peers" fails because ["peers" is required]`

This line here is causing an error   https://github.com/hyperledger/caliper/blob/7ddfe0a4c1ebd54d1fd7cdd768704d96aee80cc3/packages/caliper-fabric/lib/configValidator.js#L183

on the 2.0.0 example

https://github.com/hyperledger/caliper/blob/7ddfe0a4c1ebd54d1fd7cdd768704d96aee80cc3/packages/caliper-tests-integration/fabric_tests/phase6/networkconfig.yaml#L16

**Comment by davidkel** [comment]
Closing as this validator is only going to be relevant to the legacy fabric connectors which will be deprecated soon.
